# .docker/docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: fornovea_app
    working_dir: /var/www/html
    volumes:
      - ..:/var/www/html
    networks:
      - fornovea_network

  nginx:
    image: nginx:alpine
    container_name: fornovea_nginx
    volumes:
      - ..:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - fornovea_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: fornovea_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fornovea_db
      MYSQL_USER: fornovea_user
      MYSQL_PASSWORD: fornovea_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"  # Изменен порт на 3307
    networks:
      - fornovea_network

volumes:
  db_data:

networks:
  fornovea_network:
